modLoader="javafml"
loaderVersion="[1,)"
license="Code: MIT, Assets: All Rights Reserved"
issueTrackerURL="https://github.com/BuiltBrokenModding/MFFS_Classic/issues"

[[mods]]
modId="mffs"
version="${file.jarVersion}"
displayName="Modular Force Field System"
displayURL="https://github.com/BuiltBrokenModding/MFFS_Classic"
logoFile="logo.png"
authors="Su5eD, Built Broken Modding"
credits="Thunderdark for the original MFFS mod. Calclavia for his edition of MFFS. Art by Comply_cat_Ed, Sweet Walrus, mousecop and mr_hazard. XFactHD for helping with my rendering issues."
description='''
Modular Force Field System is a mod that adds force fields, high tech machinery and defensive measures to Minecraft.
Ever tired of nuclear explosions blowing up your house or want to keep people out of your secret bases? May the force (fields) be with you!
'''
[[mixins]]
config="mffs.mixins.json"
[[dependencies.mffs]]
    modId="neoforge"
    type="required"
    versionRange="[21.0-beta, 22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mffs]]
    modId="minecraft"
    type="required"
    versionRange="[1.21,1.22)"
    ordering="NONE"
    side="BOTH"
[[dependencies.mffs]]
    modId="theoneprobe"
    type="optional"
    versionRange="[1.21_neo-12.0.0-1, )"
    ordering="NONE"
    side="BOTH"
