name: Build with Gradle

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission to Gradle
      run: chmod +x ./gradlew

    - name: Build
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build